sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: v_nations
      - name: lineitems
      - name: orders
        config:
          freshness:
            warn_after: {count: 3, period: day}  #
            error_after: {count: 3, period: day} #if same value error takes priority over warn
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: suppliers
      - name: partsupps
      - name: parts
        

  - name: src2
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees

      